### ISSUE TITLE
【藤】点検記録にサインを貰えるようにしたい

### ISSUE THREAD

**Issue by yamadashizuka** [yamadashizuka/kilogy#37]
点検が終わった後にお客様からサインを貰えるようにしたい。

サインをする画面をどこにするかだけれど……
案１）点検記録の登録画面の最後にタブ作ってソコでやる
案２）点検記録の確認＆サイン的な画面を作って、一番下にサインするトコロを作る
　　※登録された記録を確認した後にサインするイメージ
なんとなく２かなーって思ってる。

**Comment by yamadashizuka** [comment]
開発環境(cloud9)上ではちゃんと動いたものの、herokuに上げて動かしたらエラーに。
ArgumentError (string contains null byte)
だそうです。
とりあえずログを貼っておきますが、エラーが起きたって言われてる
app/controllers/inspections_controller.rb:105:in `closeInspection'
に書いてあるのは、
@approval.signature = Base64.decode64(params[:sign].sub('data:image/png;base64,', ''))
なので、手書きった文字をパラメータで送ったらソコにnullが入ってたとか言ってるの……？？
ちょっとよーわからないので、いったんherokuはrollbackして一個前のに戻してます。

**Comment by yamadashizuka** [comment]
あ゛。
ログのテキストファイル貼ったらダメって言われた……(汗)
ので↓に直貼りします。

2015-04-14T02:23:22.907390+00:00 app[web.1]: Processing by InspectionsController#closeInspection as HTML
2015-04-14T02:23:22.949827+00:00 app[web.1]: Completed 500 Internal Server Error in 42ms
2015-04-14T02:23:22.903804+00:00 app[web.1]: Started POST "/inspections/10/close_inspection" for 158.201.127.1 at 2015-04-14 02:23:22 +0000
2015-04-14T02:23:22.907721+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"AgXOnywEa7EYhcSweNnV9bzqNJj8C7wyigJgrjL4mes=", "sign"=>"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAlgAAADICAYAAAA0n5+2AAAZVUlEQVR4nO3df4xdZ3ng8atV/vBuUWUh2KS+7/P6mMyc5x1uhKJFBMLe85zXdmooO1tHKN6aTZv1lqhAyUquttKmIllMKcJqtGErKIkSRc4WorBEWwua4tQQe+LUa1DapoVSZ8OiKJgqbSPqLYkUhEGzf9xzx9fjseeH5973vXO/H+nK45k7c57765znvO97nqfVAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwCi5EKMLMaaOAwAAYEPwWu13asekrO5NHQsAAMDYK4q4SUo7JWrzovVvp44HAABg7DntvlvU5p3a6aITr0kdDwAAwNjzof5PXu1JCfaZ1LEAgAsx+mAHWBMKYKyJ1odFbV5C/b7UsQCAK+2AqM270g6kjgUA1uTaa9/5L0Xte17th+3QLVPHAwBe434JNuc17k8dCwCsiSvrX+gtbq+Op44FAFotRrAAbAC+tNtE66clUJ4BQB5IsACMPXZkAHLDfgnA2GNHlp4vY9drvccHO+CDHfAa91/268Xfa24SbJfrxKnUjwe4UqzBAjD2SLDS8GXsitqnRO2MqM1LaU/11sLZvNPq+OW+Xvy9/k3UnhC1c66sHyDRwjhjvwRg7HGmODpNUvXxhaTq/O1lH+zhKx3BcsEeb/7enKidE7X7iiJuSv24gdUiwQIw9tiRDddFI1VaH19IqrR+0JfxplaMV63X9trT8Xqn9ef6iRbV+TGO2C8BGHvsyNZfEWLhSvvoUiNVW0N173onVUtx5Y4bRO15WiBhHLFfAjD22JGtH1/Gm5qq+OeGPVK1EkUnXuPUTveq9Nt3/HScZcoQ44D9EoCxJ6G+16sdE92+O3Us46go4ibR6oOi9q2BkarXRO3+FEnVRfGdT7JOnI+tOu7K6naSLeSKtaEAxprr3Ph6CfZ1UfuphOpdqeMZF0WIhQ/dWQl2j6idHUiszvjS7txSxjekjnFQUcTNEqp9Xu3Zfqxe7RhTh8gVI1gAxppTu1XU5l2wx1PHkitfxq5Te7+U9SFRe0bUXllIqEK/tEL1tNfqltSjVStRFHGz1+4eUXuB9VnIFQkWgLHm1T7f1GD6cOpYcrL4yj+v9uTgYvXelFt9WNR+tT0dr08d71oMrs9yaqe3bduxNXVMQB8JFoCx5crqBlH7gdf6OV9235Q6ntRcJ06JVndfokbV/VJWe9vT8fqNtG5pIMma601vxm7qmIBWiwQLwBgTre8WrY9vnfAmz64Tp5rpv3O9xf5pr/wbtS1lfINodaR53Od8aXemjgkgwQIwlooibpLSTvWmB6u9qeNJoen/92BT8bwZraq/OAlJ1UVivMoHOzDwXPzJFt2uqcPC5GprvUeCHZWy/kTqWAa5TpxqhzjrQoypYwGQIafdd2/UBc4uxOhCjEtN5W0p4xt8aXcuTAMuLFKvD49qLZULMfpgByTYrlFsbzV6dbzspcFWO6ljwmSSsrq5Sfa/kjqWVuvCkW5Rm2NkDcCSXLBPNjuv+1PHst6aqYUnnNrpooib+9/3Wt0iai9fWADUDo56kboLMTZNmV8cjC8XvSlDe6h5jk5IqB9NHRMmjy+7b/JqPxS1v01Z9qQ9FZ0L9QOLRrqPMIIF4CIbfXpQgu2S0r7XjMLcUxRxkz/fm29e1E6knAYsirjJafVcP74UMayE0/jL/eKpLlR3pI4Hk0fU/lTU5n1Z7RzphmO8yofurCvrPxK1cylGugGMoY08Pdjnp7uzovYPovb/RO17ovYVUXsll0RhIL6zfqb++dTxXIpo/aEmKf3m1lDfmDoeTBZR+/3mRPA3RrG9ga4Mg1cSn00x0g1gDInaQxLsKa92MHUsw+S0/gNRO+HVnnRaPbcts0XbovYlCfUp0SrrFkWi9dNe7WTucWLj8cE+0Euw6kPD3tZAyZKvNLUBT0mo9m2ksiwAhmhrsHeK1t8XtVddae9JHc8wuWDvbc5Av5zjWqdxuQz9gjVjG3TEE3lqh/rG5jPyF8PczgVN0dWe92H7W4e5PQCr1L86LOfFj0118pGcEaZWlDGI2k9E7bs5noVKsF1N4vKF1LFcTm/N2PmK7zkmq9iYtrz13/4LKe07ovYT/+btnWFsw5U72s2ayA29bAIYa7l3f5+k0as+UfumqM370M3ujNSFbhyHdVitVv8MP/+F+aPQP5HyGvf7YAcueVvu5yu9z1ruu5b7X+ljWvwzjfvX42RTSvtfvQst7N+vw8t3gaKMwamdllCfIrkCMpb7lM8kjV71idoXelch1b+SOpalNHV1Tojax1PHspxxWZg/bAufc6365T6WvC3385XeZy33Xcv9r/QxLf6Z0+r4euwL21rtF7U5p/XvrcPLt8CH7qwsNG6vnk5ZCgLAMnIewZrE0atWq9Vyau9vRl2eSB3LUpqd/LyofWscdvDjsjB/mBjBGu0I1np/Rqam3v6zTZL8T83f/dSWTtdf6d8FMEQ5j2D50v6DV/ualPUfpo5llFxZ3eDVnpVMazm9sRNfJ2rPiNq81+qW1PEsJ+f3ODam9fyMuE6c8sEebxKrc66sbl+vOAEMUc4HH1F7RNTmJVT7UscyarnXchK1h7zaSad2a+pYlpPzKC02LlG7p7f/sk+v5fddJ06J1p+VXtHQOVF7qT0T37HecQIYkpwTrP4ojpT121LHkkJztd5cjmesOb9vFhunWLFxrHWacInEal6C/Y9xmI4HMECCfcarHWtrvSd1LIPcjE2L2o9F7YWr37LrZ1LHk8JgTazUsSw2TkmL6PbdEuyoC/UDqWPB5FjtNOGSiZXaI1RjB8ZQzv39+l3pvdofD3tbudYCy7km1jglWOO2KB8bx0qnCaV3tTSJFbBR5Nzfb2tpHxatj7tQfWzY28p5jY5kWhNrnBKscVuUj41jJcm9CzGSWAEbjMzEvRLsKR/s4dSxLOa1frDZ4fzq8LeVdYKVZU2sdrl9pwQ76tSeTB3LSozTovxcuU6caoc4u57lDDa6lST3XuN+r/anMuHFcIENJedRCOkXACzratjbyvl5yLUmVu6lJBbL+TXO3QVrg3rvxXUryDkJnNrv9Z63+kNL/pz3JrDx5PrBdu7Gfy5q3xe1V7fOVD839O1l+jy0WnknMrmXkhiU82ucq6KImy5eG1QfYQRrdaSs9vZGsOrPLfXznEfQAaxRrgcdp9VbmgXuz45ke5k+D305JzKi9dNe7aQr619IHcvlcBBbnV4fRzvdlAphbdAVaM/Ed/Rb2yz1c69xv2j9l6LxPteJU6OOD8AQ5HrQ6ZcncFo9Nort5fo8DMo1kck9Oe0blzhzMJBczYva867ccUPqmMZZ0YnXiNpronamFeNVi3/uQozNkohvNNOwX+q37hHdvtuXsZsibgBXINeDTm/Epj7u1f7LKLaX6/MwKNcYrzQu14lTfjrODnu6aRyS6BwURdzcT65yvLp4XC08p9cuPULlQoyuaYfj+qVz1OaltKPN12ec2kFfxu5SSRqAzOR60B7lFYStVr7Pw6BcY+zHJaU97NRuXbbJ7sD3nNaP9c7Yh79gOtfnLzdeq/1O7aQE+w7J1foRrY/0rgbu3nS5+7Wn4/Wi1e6Fz0ioHxC1l5vP2Ilmv3hWQv2ohGofrxGQqVzP6kd5BWGr1Wq1td4jwY5KWX9iFNtbi1QJQn+E6aJEKdgBKetPiNq3RKuf9teYLJx5N1eaDf5/ie8tLJwe9ggWCdbyLig8PKKTm0khavf33n9raHsV41W+jDf5UH1MSvvO4s+UqD3jQvUxp9UvuxCj68SpN3bi64bwMACsVI4HnVFfQdhq5d2Spm/U7V4uuIJsiUSped98beD/r3mtHlzNCFY7xNlRLZzO8b2em5wLD4870epDUtoJH+wDV/q3XCdOuVDdIVodadZ2zYvWS31GX+klZNVxr/XnRO0eX3ZvK0Is1uEhAbicHA86o76CsNXKuyVN3yjbvQysw3nigkvzF93aM3ablNXNEuwPRW1+PQ4ew5LraG1ORO0jvbWP1e+mjmWjcWq3NqUaHlzPv1sUcZPT+G5f2m1S1odEqyNNWZeXljwpUjvWjDYf8VrdwnouYEhyPOiM+grCPsm0JU3fKNu9NK07TklpZ1xZLXsFmYRqX5OIHR5mXFcix5OJnLjOja+XYF8XtZ9KqN6VOp6Npq319uYk5PFRbrcIsWjPxHf0ertWH2zWdJ0dSLpecsE+yagWsM5yPOiI2u9IsKek7P76iLebZUuaQaJ2l1c75tWODXM7/ebX7RBnV3L/bdvefrWo/bmo/aittmOYsa1VjicTOemPsLgRJwCTohkln3el/UXqWLZ0ut6H+tdE68Oi9qMm0fonUfuChGrftm07r04dIzD2ckuwLlhkW1Z7R7ltr3awV2cqrn4R6ogURdwsamd6iaDdmTqeQS7YR0VtzpX2ydSxLCW393puvNrnmyvVPpw6lo1oaurtPytqr4raS61W65+ljqdPZuJ1UtqnLxrVUjsoZbXXl7HL6BawBrmd1adcZDsuB2Ap7Zck2N+J2ssS6veljqdvlGvE1iK393pOXFndIGo/8Fo/58vum5a8T4iR1jhXRtSe7+1jdrRTx7JYUcRNEqp9509wF0pCDN7OSGmnmvIqn+ot3CcJA5aUW1Ihag9JsKe82sFRbzu35+JyfGl39nd4uSQzo1wjthbj9PqOmmh9t2h9fGuo7r3kfcr6kFN71mvcn+uFILmT0p7qJS/121LHcjkyE6/zWu+Rsj4kofpqc8HLKxcnXEteubhUEnazzMTreN9gouR00Nka7J2i9fdF7VVX2ntGvf12uX2nBDvq1J4c9bbXQtS+IaE+1X5ztTN1LH2i9pBXO+nUbk0dy2KMYC1tpdPy5/vl2Te81s9tnan+1Sjj3Agk1I82Scgvpo5lLYoibpaZeJ3T+G5XVrd7jfuXS8LOX7U4kICF6quidp9Te78P3dlcThKBdZXTQcdPx1kJNidaH0mxfVdWNzSXN8+7UN2RIobV2DJT7c2tOGpOCftiOb3Xc7KaaXkJtssFe1F6BWLPidqXJNguGhSvjITq3qZEwgdTxzIsi5MwF+yjTuvHmn3r4gRs7oLES+vDMlP9hgsxMtqFsZfTATGHWHo9EG1e1L65NdQ3popjJXyIs82B8WupY+nL4TW8lJxjS8kF+2Tznr9/Jfcviri538qq1zOvOiJq53yoHyDRujxRu6vXtH1yk/yiE6/xZey6srpdtL67Gc06u0TS9VqvhdYaKt8DOcjpoOO0fkyCza20NMCwiNZf9mrHnNp/TxnHcrbOVD8nan8ramdlase1qeNptfIeJco5tlSu5KrdXs+87bt906C4P6pFonVpOe1vc+M6ccprdYsr6//an0lobvekjg1Yk1w+8KnXXw1yoRtF7R9E7ayfqX8+ZSzLEbUv9xaV279LHUurlc/7aSk5x5bKel21256O1zetWBYSLVH7Uq81Ur2HKZ8e3oMrVxRxs5TVzaNqpQWsu1zO6lOvv1pM1H5f1OZ9qEbS92+tegtN7Zho/XQOLS9yeT8tJZcR0pyI1r+93NWDqzGYaLnzl/sfZcqnhwQLmCC5fOBzOzAPjmJtnan+Tep4LqUpPPpCLkPpubyfFstphDQXwyzqOzB9eKAp4Lsw5dM7IUj/Xk0h188HgCHI5QOfSxyDRO2+Zrrj+VEXPV0NUftF0er/itqPU1/9mFui3Cdaf7Y3QmqPpI4lF6Mu6tucDNwlwf5R1M5unc73xGVYctzPARiSXA6IucQxqNel3k6P8iC0VlLWvy69nmLflbK6OVUcOb6OjF4tbbVXD66X/omLU3t+0nrekWABEySXD3yOB+ZWq3dJ8QVJVhE3p47pUkTtnuaA+UKqwn05vo65re/LQcqenwMnLnO5f6bWm+j23RLsqAt11ms7AawDEqzlFZ14jQv2ooT6VNa92GK8SkL1Zymru7sQow92IKfnKZf3eE5S9vxstVqtbdt2Xi1qL0qwUxJs16i3n0ru/ToBrKNcDj45HpgHyVRz5pl5G532m6udovaEU/vfqWPJQa+BbfyMaP2XOSbvqYjaR0Tr416r300VQ7tXKPcJF+zFSRnFyr1fJ4B11NZ6T27tVnI0Lm10moXEZ0Rt3pd2Z+p4UvLTcbZp6/IN0ep4rsn7qLnOja+XYF8XtZ9KqN6VKo6iiJv6o1iT9NosTOUH+3TqWAAMkQv23mbI+supY8ndQBudv8m5l5iU9ksS7O9E7WUJ9fvW+nf6o4oX3TTuX9H3lvrZcr/bfL2aA+5CnIv+jqjNSWnfbg7iEzMNtRyndmvvRMEeTx5LaQebz9THU8cyKkwTAhOiKGMQtZ+I2neptLw80frwQK+sM6J2V+qYluJLu7Mf41p34v3p48U3p9XxlXxvqZ8t97v9r1czZb0wzb3Udsr60KRMP62UV/t8UwD0w6ljcSHGhWnCjK/SXU9MEwITRNS+2ata3n1r6lhy5zpxSkp7WNRebYomnsx1dETU/kTU5iRU/20tvz/uI1g5r+lLxZXVDaL2A6/1c77svil1PBeVQpmQZNj1CrAe81o/mDoWAEMkal/ordmpfyV1LLkpirjJhRi9xv1O68dE7ZxoddxpNdckMCd8aX/vp/Nrv9Iuq50yJj0VMRpbZ6rbvdqTEuwzqWPpKzrxmklbizVO/U4BXIGmlcVJ0fpDqWPJSVHEzb2z6+pIM+XUTA3WR5qyEruc2mlX2qnUV2FeioxJT0WMhqg90ltgXe1LHcsgX9a/lWuZlmGRsj4kaidE7SOpYwEwJP11EKKTsw5iOVvK+AYJ9psS7Nu+tL+XYL/ZDnF2cWf3ooibXYgx1zPvcempiNFY6AlY1m9LHcugXMrFjJLX6l87tR9KWf31lk7Xp44HwBBcsA4i2Itbp+29rhOnUseVitfqFlF7WdT+StTm2iG/6b/VkMGeihOyxgUXczM2LWo/FrUXrn7Lrp9JHc+gSUywWq1WS9T+Z2+E2T6QOhYAQ9JvCeN67TOe6K01svsm5cpC14lTTUuVowtXuIXqz3IdmVqN3joye1GCfXuSpmBwISmrm5sLM/44dSyL5dzJYZgkVPuaZQeHU8cCYIjOT3fZ402SMeeCvejVDvavzhLdvtuXsZs61vXSuyqwPnR+8bodE7VXci4muhZ+Os6KVselrA+ljgVp+NJuE62fFrV7Usey2KSOYG3b9varRe3PRe1HbbUdqeMBMAKu3HGDqD3v+g1h+7dyYYTnjIT6Xh+6s0WIRep4V6s9FZ0P1QPNSN18f/F6u9y+cxwfz0rkvFYMw5dzEpNzbMMmavd5tZNe6z2pYwEwIv0RrcGaRS7UDzTrk+YHCm7Oi9orovaMlPUhp/Z+H7qz2VUpjvEqH7qzrqz/SNTOSbCn+sPzixevAxtNzknMpE4Rtlp5vy4ARi3Gq3wZb3KhukO0PtxfID9wG0y8zojWhwenGVdUoPJyhSvX8HsS6nubyuv9uM56tYMkVpgUOR/Ic45t2PqPva32O6ljAZChooib2tPxeimrvaL13RKqr4ra2fOtS+zkcm1UVvL9tf5es7ZqXko7JaHaNymL94G+nEeJJjrBokwOgLVwnTjltbrFlfH2pCNYun23zMTrUj8fQCo5JzE5J3/DNqntggAA2BBEt++WYEddqLOr6p9z8jcKRSdeQykVAADGkA/d2WbK/Fu5XYDitH5Mgs3l2NNzVCilAgDAGHpjJ75O1J7pJVnd/5g6nr6twd4pWn9f1F51pb0ndTwpUUoFAIAxJGp3NVf5/qPX6pbU8bRarZZo/VkJNidqj6SOBQAAYE0k1I+ebwdVP5ryilpGrwAAwIbR9MA769WOObXTqcoD+LL6Ld8rofLFFNsHAABYVzK141pR+z9N/bjnZGrHtaPcflHETdJvxVVWe0e5bQAAgKEpOvGapgbTCVF7eZTrsqS0/7xQ+4kCmwAAYCMpirj5gnVZWn/RdeLUMLblOnFKtLr7fNuq6mkfJrP2FQAAmACD67JE7ZzT+g9ciHE9FsH7Mna91g+K2jnfb1ul9jLJFQAA2PDaU9FJaQ83CdCJ5t/XpNfj854l21Itbk818H9Ru29htCrYU/0RMl/Gm1oxXpX68QIAAIxMezpe70J1h1d79lIN2/uN1Rc3WB/8vxscrVI72J6O16d+bAAAAMkVRdwsZXXzRQ3bVzCC1dZ6D6NVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAN4P8DA/jSiC+vdwkAAAAASUVORK5CYII=", "commit"=>"点検完了(承認)", "id"=>"10"}
2015-04-14T02:23:22.951713+00:00 app[web.1]: 
2015-04-14T02:23:22.951718+00:00 app[web.1]:   app/controllers/inspections_controller.rb:105:in `closeInspection'
2015-04-14T02:23:22.951716+00:00 app[web.1]: ArgumentError (string contains null byte):
2015-04-14T02:23:22.951719+00:00 app[web.1]: 
2015-04-14T02:23:22.951720+00:00 app[web.1]: 
2015-04-14T02:23:23.200517+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=kilogy-test.herokuapp.com request_id=76875e4f-59ce-45d6-beea-8c66ceba981f fwd="unknown,158.201.127.1" dyno=web.1 connect=2ms service=5ms status=200 bytes=228

**Comment by yamadashizuka** [comment]
herokuに上げないと現象が確認できないので、デバッグ用にいっこアプリつくりました。
http://kilogy-debug.herokuapp.com/

**Comment by yamadashizuka** [comment]
とりあえず、
@approval.signature = Base64.decode64(params[:sign].sub('data:image/png;base64,', ''))
を二行に分割して、
p=params[:sign].sub('data:image/png;base64,', '')
@approval.signature = Base64.decode64(p)
ってしたら、二行目の方で落ちた。
疑うべきはpの中身？

**Comment by yamadashizuka** [comment]
本日(2015/4/16)の実験。
山海さんのレポジトリにある手書きのサンプル(https://github.com/sankai/autograph)をherokuにデプロイして試しに動かしてみたところ、やっぱり同じエラーが出た。

app/controllers/autographs_controller.rb:29:in `create'
ArgumentError (string contains null byte):
でした。

**Comment by yamadashizuka** [comment]
本日(2015/4/16)の実験その２。

herokuのrubyのversionがcloud9よりも古かったので、とりあえず同じ(新しい)バージョンを使うように、
Gemfile に
ruby '2.1.5'
って書き足してやってみた……けど、現象かわらずでした。

**Comment by yamadashizuka** [comment]
Base64.decode64 については色々手詰まり感アリなので、諦めて別の方法にしました。(#61)
ってことで、canvas にお絵描きする用のjavascript で、fabric ( http://fabricjs.com/ ) というのがお勧めされてたので、それを使う方法に変更しました。
保存(と表示)はＳＶＧで。

**Comment by yamadashizuka** [comment]
という訳で、とりあえず実現できたのでCloseします。
